---
title: "vdb_poster_plot_notebook"
---
## Instalation des packages

```{r,include=FALSE}
if (!requireNamespace('pak',quietly = TRUE))
  install.packages('pak')

library_list <- c('tidyverse','phyloseq','ggplot2','here','dplyr','umap','tibble','tidyr','vegan','stringr')

if (!requireNamespace(library_list, quietly = TRUE))
  pak::pkg_install(library_list)

#certaines libraries ne s'installent pas correctement avec pak
if (!require("plotly", quietly = TRUE)) {
  install.packages("plotly")
}
if (!require("ggalluvial", quietly = TRUE)) {
  install.packages("ggalluvial")
}
if (!require("umap", quietly = TRUE)) {
  install.packages("umap")
}
if (!require("gridExtra", quietly = TRUE)) {
  install.packages("gridExtra")
}
```

## Chargement des packages

```{r}
library(tidyverse)
library(phyloseq)
library(ggplot2)
library(here)
library(dplyr)
library(ggalluvial)
library(plotly)
library(umap)
library(tibble)
library(tidyr)
library(vegan)
library(phyloseq)
library(stringr)
```

## Chargement des données

```{r}
# --- Chargement des données ---
path_data <- "data/raw"
path_figs <- "results/figures"

# Métadonnées
meta_df <- read.csv(here(path_data, "metadata500_starters.csv"), row.names = 1)

# Table d'abondance - 16S
ab_16s_df <- read.csv(here(path_data, "sourdough_tab_16S.csv"), row.names = 1)

# Taxonomie - 16S
tax_16s_df <- read.csv(here(path_data, "sourdough_tax_16S.csv"), row.names = 1)

# Table d'abondance - ITS
ab_its_df <- read.csv(here(path_data, "sourdough_tab_ITS.csv"), row.names = 1)

# Taxonomie - ITS
tax_its_df <- read.csv(here(path_data, "sourdough_tax_ITS.csv"), row.names = 1)
```

## Nettoyage et création objets phyloseq

```{r}
# --- Nettoyage et Renommage de la Taxonomie ---

# 16S
tax_16s_mat <- tax_16s_df %>%
  rename(
    Kingdom = taxonomy1, Phylum = taxonomy2, Class = taxonomy3,
    Order = taxonomy4, Family = taxonomy5, Genus = taxonomy6,
    Species = taxonomy7, ASV = taxonomy8
  ) %>%
  as.matrix()

# ITS 
tax_its_mat <- tax_its_df %>%
  rename(
    Kingdom = taxonomy1, Phylum = taxonomy2, Class = taxonomy3,
    Order = taxonomy4, Family = taxonomy5, Genus = taxonomy6,
    Species = taxonomy7, ASV = taxonomy8
  ) %>%
  as.matrix()

# --- Conversion en matrices pour phyloseq ---
ab_16s_mat <- as.matrix(ab_16s_df)
ab_its_mat <- as.matrix(ab_its_df)

# --- Vérification de la correspondance des IDs ---
common_samples <- Reduce(intersect, list(colnames(ab_16s_mat), colnames(ab_its_mat), rownames(meta_df)))

print(paste("Nombre d'échantillons conservés (communs 16S & ITS) :", length(common_samples)))

# On filtre les trois tables pour qu'elles soient parfaitement alignées
ab_16s_mat <- ab_16s_mat[, common_samples]
ab_its_mat <- ab_its_mat[, common_samples]
meta_df    <- meta_df[common_samples, ]

# --- Création des objets Phyloseq ---

# 16S
phylos_16s <- phyloseq(
  otu_table(ab_16s_mat, taxa_are_rows = TRUE),
  tax_table(tax_16s_mat),
  sample_data(meta_df)
)

# ITS
phylos_its <- phyloseq(
  otu_table(ab_its_mat, taxa_are_rows = TRUE),
  tax_table(tax_its_mat),
  sample_data(meta_df)
)

# Nettoyage taxons vides
phylos_its <- prune_taxa(taxa_sums(phylos_its) > 0, phylos_its)
phylos_16s <- prune_taxa(taxa_sums(phylos_16s) > 0, phylos_16s)

print("--- Résumé 16s ---")
print(phylos_16s)
print("--- Résumé ITS ---")
print(phylos_its)
```

## PCoA

```{r}
# --- PCoA 16S ---
dist_mat_16s <- phyloseq::distance(phylos_16s, method = "bray")
pcoa_16s     <- ordinate(phylos_16s, method = "PCoA", distance = dist_mat_16s)

# Variance 16S
eig_16s <- pcoa_16s$values$Relative_eig
cat("16S - Variance expliquée par les 10 premiers axes:\n")
print(cumsum(eig_16s)[1:10])

n_axes_16s <- which(cumsum(eig_16s) >= 0.75)[1]
cat("16S - Nombre d'axes pour 75% variance:", n_axes_16s, "\n")

# Clustering 16S
coords_16s <- pcoa_16s$vectors[, 1:n_axes_16s]
kmeans_16s <- kmeans(coords_16s, centers = 8, nstart = 25, iter.max = 100)
sample_data(phylos_16s)$Cluster <- as.factor(kmeans_16s$cluster)


# --- PCoA ITS ---
dist_mat_its <- phyloseq::distance(phylos_its, method = "bray")
pcoa_its     <- ordinate(phylos_its, method = "PCoA", distance = dist_mat_its)

# Variance ITS
eig_its <- pcoa_its$values$Relative_eig
cat("ITS - Variance expliquée par les 10 premiers axes:\n")
print(cumsum(eig_its)[1:10])

n_axes_its <- which(cumsum(eig_its) >= 0.75)[1]
cat("ITS - Nombre d'axes pour 75% variance:", n_axes_its, "\n")

# Clustering ITS
coords_its <- pcoa_its$vectors[, 1:n_axes_its]
kmeans_its <- kmeans(coords_its, centers = 10, nstart = 25, iter.max = 100)
sample_data(phylos_its)$Cluster <- as.factor(kmeans_its$cluster)
```

## Elbow plot

```{r}
# --- Fonction utilitaire pour calculer le WSS ---
calculate_wss_df <- function(coordinates, max_k = 10) {
  wss <- numeric(max_k)
  for (k in 1:max_k) {
    set.seed(42)
    km_res <- kmeans(coordinates, centers = k, nstart = 25, iter.max = 100) # Calcul kmeans
    wss[k] <- km_res$tot.withinss # On stocke la somme des carrés intra-cluster
  }
  return(data.frame(k = 1:max_k, wss = wss))
}

# --- 1. Préparation des données (au cas où) ---
# On s'assure d'avoir les coordonnées basées sur les axes retenus précédemment
coords_16s <- pcoa_16s$vectors[, 1:n_axes_16s]
coords_its <- pcoa_its$vectors[, 1:n_axes_its]

# --- Calcul des Elbows ---

# 16S
elbow_data_16s <- calculate_wss_df(coords_16s, max_k = 10)

# ITS
elbow_data_its <- calculate_wss_df(coords_its, max_k = 10)

# --- Plots ---

# 16S
p_elbow_16s <- ggplot(elbow_data_16s, aes(x = k, y = wss)) +
  geom_line(color = "steelblue", size = 1) +
  geom_point(color = "steelblue", size = 3) +
  scale_x_continuous(breaks = 1:10) +
  theme_bw() +
  labs(title = "Elbow Plot - 16S",
       x = "Nombre de clusters (k)",
       y = "Total Within Sum of Squares")

# ITS
p_elbow_its <- ggplot(elbow_data_its, aes(x = k, y = wss)) +
  geom_line(color = "darkorange", size = 1) +
  geom_point(color = "darkorange", size = 3) +
  scale_x_continuous(breaks = 1:10) +
  theme_bw() +
  labs(title = "Elbow Plot - ITS",
       x = "Nombre de clusters (k)",
       y = "Total Within Sum of Squares")

print(p_elbow_16s)
print(p_elbow_its)
```

## PCoA 2D plot

```{r}
# --- Plot 16S ---
p_kmeans_16s <- plot_ordination(phylos_16s, pcoa_16s, color = "Cluster") +
  geom_point(size = 2, alpha = 0.7) +
  stat_ellipse(type = "norm", linetype = 2) +
  theme_bw() +
  labs(title = "Beta-Diversité 16S (distance = Bray-Curtis)", 
       color = "Cluster 16S")

# --- Plot ITS ---
p_kmeans_its <- plot_ordination(phylos_its, pcoa_its, color = "Cluster") +
  geom_point(size = 2, alpha = 0.7) +
  stat_ellipse(type = "norm", linetype = 2) +
  theme_bw() +
  labs(title = "Beta-Diversité ITS (distance = Bray-Curtis)", 
       color = "Cluster ITS")

print(p_kmeans_16s)
print(p_kmeans_its)
```

## Sankey plot : comparaison clustering 16s vs ITS 

```{r}
# --- Préparation des données ---

# Extraction des clusters
# 16S
df_clus_16s <- data.frame(
  SampleID = rownames(sample_data(phylos_16s)),
  Cluster_16S = sample_data(phylos_16s)$Cluster
)

# ITS
df_clus_its <- data.frame(
  SampleID = rownames(sample_data(phylos_its)),
  Cluster_ITS = sample_data(phylos_its)$Cluster
)

# Fusion des deux df
df_alluvial <- inner_join(df_clus_16s, df_clus_its, by = "SampleID")

df_alluvial <- df_alluvial %>%
  group_by(Cluster_16S, Cluster_ITS) %>%
  summarise(Freq = n(), .groups = "drop")

# --- Plot Alluvial ---
p_sankey <- ggplot(df_alluvial,
       aes(y = Freq, axis1 = Cluster_16S, axis2 = Cluster_ITS)) +
  
  # Lien
  geom_alluvium(aes(fill = Cluster_16S), width = 1/12, alpha = 0.7) +
  
  # Clusters
  geom_stratum(width = 1/6, fill = "grey90", color = "grey") +
  
  # Texte clusters
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 3) +
  
  theme_minimal() +
  labs(title = "Correspondance entre clustering sur 16S et sur ITS",
       y = "Nombre d'échantillons") +
  theme(legend.position = "none")

print(p_sankey)
```
## PCoA 3D plot

```{r}

# --- PCoA 3D plot - 16S ---

# Extraire les coordonnées axes 1à3
coord_3d_16s <- as.data.frame(pcoa_16s$vectors[, 1:3])
colnames(coord_3d_16s) <- c("Axis1", "Axis2", "Axis3")

# Métadonnées
meta_df_16s <- data.frame(sample_data(phylos_16s))
meta_df_16s$SampleID <- rownames(meta_df_16s)
coord_3d_16s$SampleID <- rownames(coord_3d_16s)

# Fusion : meta - coord
plot_data_16s <- merge(coord_3d_16s, meta_df_16s, by = "SampleID")

# Plot : plotly
p_3d_16s <- plot_ly(
  data = plot_data_16s,
  x = ~Axis1,
  y = ~Axis2,
  z = ~Axis3,
  color = ~Cluster,
  colors = "Set1",
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 5, opacity = 0.8),
  text = ~paste("Sample:", SampleID, "<br>Cluster 16S:", Cluster)
) %>%
  layout(
    title = "Beta-Diversité ITS (distance = Bray-Curtis) - 3D",
    scene = list(
      xaxis = list(title = "PCoA 1"),
      yaxis = list(title = "PCoA 2"),
      zaxis = list(title = "PCoA 3")
    )
  )


# --- PCoA 3D plot - ITS ---

# Extraire les coordonnées axes 1à3
coord_3d_its <- as.data.frame(pcoa_its$vectors[, 1:3])
colnames(coord_3d_its) <- c("Axis1", "Axis2", "Axis3")

# Métadonnées
meta_df_its <- data.frame(sample_data(phylos_its))
meta_df_its$SampleID <- rownames(meta_df_its)
coord_3d_its$SampleID <- rownames(coord_3d_its)

# Fusion : meta - coord
plot_data_its <- merge(coord_3d_its, meta_df_its, by = "SampleID")

# Plot : plotly
p_3d_its <- plot_ly(
  data = plot_data_its,
  x = ~Axis1,
  y = ~Axis2,
  z = ~Axis3,
  color = ~Cluster,
  colors = "Set1",
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 5, opacity = 0.8),
  text = ~paste("Sample:", SampleID, "<br>Cluster ITS:", Cluster)
) %>%
  layout(
    title = "Beta-Diversité ITS (distance = Bray-Curtis) - 3D",
    scene = list(
      xaxis = list(title = "PCoA 1"),
      yaxis = list(title = "PCoA 2"),
      zaxis = list(title = "PCoA 3")
    )
  )

# --- Affichage ---
p_3d_16s
p_3d_its
```

## UMAP

```{r, fig.width=5, fig.height=4}

# --- Fonction : calcul et formatage UMAP vers un df pour ggplot ---
run_umap_phyloseq <- function(phyloseq_obj, n_neighbors = 30, min_dist = 0.6) {
  
  # 1. Préparation des données : Normalisation Relative
  ps_rel <- transform_sample_counts(phyloseq_obj, function(x) x / sum(x))
  
  # 2. Extraction de la table d'OTU (Samples en lignes, ASV en colonnes)
  otu_mat <- as(otu_table(ps_rel), "matrix")
  # Si les taxa sont en lignes, on transpose pour avoir les samples en lignes
  if(taxa_are_rows(ps_rel)) {
    otu_mat <- t(otu_mat)
  }
  
  # 3. Parametres UMAP
  custom_config <- umap.defaults
  custom_config$n_neighbors <- n_neighbors
  custom_config$min_dist <- min_dist
  custom_config$random_state <- 42 # Seed pour avoir toujours le même dessin
  
  # 4. Exécution
  umap_res <- umap(otu_mat, config = custom_config)
  
  # 5. Df pour ggplot
  df_umap <- as.data.frame(umap_res$layout)
  colnames(df_umap) <- c("UMAP1", "UMAP2")
  
  # 6. Ajout métadonnées
  meta <- as(sample_data(phyloseq_obj), "data.frame")
  meta$SampleID <- rownames(meta)
  df_umap$SampleID <- rownames(df_umap)
  
  df_final <- left_join(df_umap, meta, by = "SampleID")
  
  return(df_final)
}

# --- Calcul UMAPs ---

df_umap_16s <- run_umap_phyloseq(phylos_16s)
df_umap_its <- run_umap_phyloseq(phylos_its)

# --- Plots ---

# 16S
p_umap_16s <- ggplot(df_umap_16s, aes(x = UMAP1, y = UMAP2, color = Cluster)) +
  geom_point(size = 2, alpha = 0.7) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), # Enlève la grosse grille
    panel.grid.minor = element_blank(), # Enlève la petite grille
    strip.background = element_rect(fill = "white"), # Fond des titres de facettes en blanc
    axis.text = element_blank(), # Enlève les chiffres des axes (inutiles en UMAP)
    axis.ticks = element_blank() # Enlève les petits traits des axes
  ) +
  labs(title = "UMAP - 16S (Bactéries)",
       color = "Cluster 16S")

# ITS
p_umap_its <- ggplot(df_umap_its, aes(x = UMAP1, y = UMAP2, color = Cluster)) +
  geom_point(size = 2, alpha = 0.7) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), # Enlève la grosse grille
    panel.grid.minor = element_blank(), # Enlève la petite grille
    strip.background = element_rect(fill = "white"), # Fond des titres de facettes en blanc
    axis.text = element_blank(), # Enlève les chiffres des axes (inutiles en UMAP)
    axis.ticks = element_blank() # Enlève les petits traits des axes
  ) +
  labs(title = "UMAP - ITS (Levures)",
       color = "Cluster ITS")

print(p_umap_16s)
print(p_umap_its)

# --- Save plot ---
ggsave(
  filename = here(path_figs, "p_umap_16s.svg"),
  plot = p_umap_16s,
  width = 5,
  height = 4,
  device = "svg"
)

ggsave(
  filename = here(path_figs, "p_umap_its.svg"),
  plot = p_umap_its,
  width = 5,
  height = 4,
  device = "svg"
)
```

## Top ASV structurants les données

```{r}
# --- Fonction : Trouver les top ASV corrélés aux axes ---
get_pcoa_drivers <- function(phyloseq_obj, pcoa_obj, n_top = 10) {
  
  # 1. Récupérer la table d'OTU normalisée
  ps_rel <- transform_sample_counts(phyloseq_obj, function(x) x / sum(x))
  otu_mat <- as(otu_table(ps_rel), "matrix")
  if(taxa_are_rows(ps_rel)) otu_mat <- t(otu_mat) 
  
  # 2. Récupérer les coordonnées
  axes_coords <- pcoa_obj$vectors[, 1:2]
  colnames(axes_coords) <- c("Axis1", "Axis2")
  
  # 3. Calculer les corrélations
  cor_res <- data.frame(
    ASV = colnames(otu_mat), # Ici "ASV" contient l'identifiant (ex: ASV1)
    Cor_Axis1 = numeric(ncol(otu_mat)),
    Cor_Axis2 = numeric(ncol(otu_mat)),
    stringsAsFactors = FALSE
  )
  
  for(i in 1:ncol(otu_mat)) {
    cor_res$Cor_Axis1[i] <- cor(otu_mat[, i], axes_coords[, "Axis1"], method = "spearman")
    cor_res$Cor_Axis2[i] <- cor(otu_mat[, i], axes_coords[, "Axis2"], method = "spearman")
  }
  
  # 4. Score d'importance
  cor_res$Importance <- (abs(cor_res$Cor_Axis1) + abs(cor_res$Cor_Axis2)) / 2
  
  # 5. Ajouter la taxonomie
  tax_df <- as.data.frame(tax_table(phyloseq_obj))
  tax_df$ASV_ID_JOIN <- rownames(tax_df)
  
  # On fait la jointure entre "ASV" (de cor_res) et "ASV_ID_JOIN" (de tax_df)
  res_final <- left_join(cor_res, tax_df, by = c("ASV" = "ASV_ID_JOIN")) %>%
    arrange(desc(Importance)) %>%
    head(n_top)
  
  return(res_final)
}

# --- Drivers : 16S ---
ps_16s_filt <- prune_taxa(taxa_sums(phylos_16s) > 0, phylos_16s) 
drivers_16s <- get_pcoa_drivers(ps_16s_filt, pcoa_16s, n_top = 8)

print(drivers_16s %>% select(ASV, Genus, Species, Cor_Axis1, Cor_Axis2))

# --- Drivers : ITS ---
ps_its_filt <- prune_taxa(taxa_sums(phylos_its) > 0, phylos_its)
drivers_its <- get_pcoa_drivers(ps_its_filt, pcoa_its, n_top = 8)

print(drivers_its %>% select(ASV, Genus, Species, Cor_Axis1, Cor_Axis2))
```
## Plot ASV structurants sur UMAP

```{r, fig.width=8, fig.height=3}
# --- 16S ---

# Préparation données
# target_asvs_16s <- drivers_16s$ASV
target_asvs_16s <- c('ASV_4','ASV_3','ASV_7') # ASV d'interet après visu sur UMAP
ps_drivers_16s <- prune_taxa(target_asvs_16s, phylos_16s)

df_taxa_16s <- psmelt(ps_drivers_16s)

# Netoyage des noms 
df_taxa_16s <- df_taxa_16s %>%
  mutate(
    Genus_Clean = str_replace_all(Genus, "g__", ""),
    Genus_Clean = str_replace_all(Genus_Clean, "__", ""),
    Species_Clean = str_replace_all(Species, "s__", ""),
    Species_Clean = str_replace_all(Species_Clean, "__", " "),
    
    PlotLabel = paste(Genus_Clean,' ', Species_Clean, "\n(", OTU, ")", sep = "")
  )

# Normalisation "Intra-ASV"
df_taxa_norm_16s <- df_taxa_16s %>%
  group_by(PlotLabel) %>%
  mutate(Max_Abundance = max(Abundance, na.rm = TRUE)) %>%
  mutate(Normalized_Abundance = ifelse(Max_Abundance == 0 | is.na(Max_Abundance), 
                                       0, 
                                       Abundance / Max_Abundance)) %>%
  ungroup()

# Fusion avec coordonnées UMAP
umap_coords_16s <- df_umap_16s %>% 
  select(SampleID, UMAP1, UMAP2) 

df_plot_umap_16s <- left_join(df_taxa_norm_16s, umap_coords_16s, by = c("Sample" = "SampleID"))

# Plot
p_MO_struct_16s <- ggplot(df_plot_umap_16s, aes(x = UMAP1, y = UMAP2)) +
  # Points colorés par l'abondance
  geom_point(aes(color = Normalized_Abundance), size = 1.5, alpha = 0.9, na.rm = TRUE) +
  # Facettes par Bactérie
  facet_wrap(~PlotLabel, ncol = 4) + 
  # Couleurs
  scale_color_viridis_c(option = "plasma", 
                        name = "Abondance Relative\n(Normalisé)",
                        breaks = c(0, 0.5, 1),
                        labels = c("Absent", "Moyen", "Max obs."),
                        na.value = "grey90") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), # Enlève la grosse grille
    panel.grid.minor = element_blank(), # Enlève la petite grille
    strip.background = element_rect(fill = "white"), # Fond des titres de facettes en blanc
    strip.text = element_text(face = "bold", size = 9), # Titres des ASV en italique
    axis.text = element_blank(), # Enlève les chiffres des axes (inutiles en UMAP)
    axis.ticks = element_blank() # Enlève les petits traits des axes
  ) +
  labs(title = "16S : Abondance relatives de MO structurants visualisés sur l'UMAP",
       x = "UMAP 1\n→", y = "→\nUMAP 2")


# --- ITS ---

# Préparation données
# target_asvs_its <- drivers_its$ASV
target_asvs_its <- c('ASV_1','ASV_4','ASV_5')  # ASV d'interet après visu sur UMAP
ps_drivers_its <- prune_taxa(target_asvs_its, phylos_its)

df_taxa_its <- psmelt(ps_drivers_its)

# Netoyage des noms 
df_taxa_its <- df_taxa_its %>%
  mutate(
    Genus_Clean = str_replace_all(Genus, "g__", ""),
    Genus_Clean = str_replace_all(Genus_Clean, "__", ""),
    Species_Clean = str_replace_all(Species, "s__", ""),
    Species_Clean = str_replace_all(Species_Clean, "__", " "),

    PlotLabel = paste(Genus_Clean,' ', Species_Clean, "\n(", OTU, ")", sep = "")
  )

# Normalisation "Intra-ASV"
df_taxa_norm_its <- df_taxa_its %>%
  group_by(PlotLabel) %>%
  mutate(Max_Abundance = max(Abundance, na.rm = TRUE)) %>%
  mutate(Normalized_Abundance = ifelse(Max_Abundance == 0 | is.na(Max_Abundance), 
                                       0, 
                                       Abundance / Max_Abundance)) %>%
  ungroup()

# Fusion avec coordonnées UMAP
umap_coords_its <- df_umap_its %>% 
  select(SampleID, UMAP1, UMAP2)

df_plot_umap_its <- left_join(df_taxa_norm_its, umap_coords_its, by = c("Sample" = "SampleID"))

# Plot
p_MO_struct_its <- ggplot(df_plot_umap_its, aes(x = UMAP1, y = UMAP2)) +
  geom_point(aes(color = Normalized_Abundance), size = 1.5, alpha = 0.9, na.rm = TRUE) +
  facet_wrap(~PlotLabel, ncol = 4) +
  scale_color_viridis_c(option = "plasma", 
                        name = "Abondance Relative\n(Normalisé)",
                        breaks = c(0, 0.5, 1),
                        labels = c("Absent", "Moyen", "Max obs."),
                        na.value = "grey90") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), # Enlève la grosse grille
    panel.grid.minor = element_blank(), # Enlève la petite grille
    strip.background = element_rect(fill = "white"), # Fond des titres de facettes en blanc
    strip.text = element_text(face = "bold", size = 9), # Titres des ASV en italique
    axis.text = element_blank(), # Enlève les chiffres des axes (inutiles en UMAP)
    axis.ticks = element_blank() # Enlève les petits traits des axes
  ) +
  labs(title = "ITS : Abondance relatives de MO structurants visualisés sur l'UMAP",
       x = "UMAP 1\n→", y = "→\nUMAP 2")


print(p_MO_struct_16s)
print(p_MO_struct_its)

# --- Save plot ---

ggsave(
  filename = here(path_figs, "p_MO_struct_16s.svg"),
  plot = p_MO_struct_16s,
  width = 8,
  height = 3,
  device = "svg"
)

ggsave(
  filename = here(path_figs, "p_MO_struct_its.svg"),
  plot = p_MO_struct_its,
  width = 8,
  height = 3,
  device = "svg"
)
```

## PERMANOVA

```{r}
# Variables à tester
vars_to_test <- c("Country", "StorageLocBin", "WhoMadeBin", 
                  "Starter.age.years", "FreqOpenedPerWeek", 
                  "ContainerMaterial", "Temp")

# Netoyage metadonnées
meta_full <- as(sample_data(phylos_16s), "data.frame") %>%
  select(all_of(vars_to_test))

# Conversion des types
meta_full <- meta_full %>%
  mutate(
    Country           = as.factor(Country),
    StorageLocBin     = as.factor(StorageLocBin),
    WhoMadeBin        = as.factor(WhoMadeBin),
    ContainerMaterial = as.factor(ContainerMaterial),
    Starter.age.years = as.numeric(Starter.age.years),
    FreqOpenedPerWeek = as.numeric(FreqOpenedPerWeek),
    Temp              = as.numeric(Temp)
  )

# Gestion des NA
n_before <- nrow(meta_full)
meta_clean <- na.omit(meta_full)
n_after <- nrow(meta_clean)
samples_kept <- rownames(meta_clean)

cat("Échantillons initiaux :", n_before, "\n")
cat("Échantillons conservés (aucun NA) :", n_after, "\n")

# 16s
mat_16s_subset <- as.matrix(dist_mat_16s)[samples_kept, samples_kept]
dist_clean_16s <- as.dist(mat_16s_subset)

# ITS
mat_its_subset <- as.matrix(dist_mat_its)[samples_kept, samples_kept]
dist_clean_its <- as.dist(mat_its_subset)

# ---Calcul PERMANOVA ---

#16S
cat("\n========================================\n")
cat(" PERMANOVA - 16S \n")
cat("========================================\n")
# by = "margin" teste l'effet unique de chaque variable (Type III sum of squares : ANOVA III) : test chaque variable comme si elle etait la derniere a rentrer dans le modèle
permanova_16s <- adonis2(dist_clean_16s ~ ., data = meta_clean, permutations = 999, by = "margin")
print(permanova_16s)

# PERMANOVA ITS
cat("\n========================================\n")
cat(" PERMANOVA - ITS\n")
cat("========================================\n")
permanova_its <- adonis2(dist_clean_its ~ ., data = meta_clean, permutations = 999, by = "margin")
print(permanova_its)
```

## Plot PERMANOVA

```{r, fig.width=6, fig.height=4}
# --- Fonction : Nettoyer résultats PERMANOVA ---
clean_permanova_plot <- function(permanova_res, dataset_name) {
  df <- as.data.frame(permanova_res)
  df$Variable <- rownames(df)
  df$Percent <- df$R2 * 100
  df$Dataset <- dataset_name # Pour distinguer 16S et ITS
  
  # On catégorise : Residual vs Métadonnées
  df$Type <- ifelse(df$Variable == "Residual", "Non Expliqué (Biologique)", "Métadonnées")
  
  # On filtre la ligne "Total" qui vaut toujours 100% et écrase le reste
  df <- df %>% filter(Variable != "Total")
  
  return(df)
}

# --- Clean res PERMANOVA ---
df_res_16s <- clean_permanova_plot(permanova_16s, "16S")
df_res_its <- clean_permanova_plot(permanova_its, "ITS")

# Fusion des res
df_permanova_combined <- rbind(df_res_16s, df_res_its)

# --- 3. Le Graphique Comparatif ---
p_permanova_combined <- ggplot(df_permanova_combined, aes(x = reorder(Variable, Percent), y = Percent, fill = Type)) +
  geom_bar(stat = "identity", width = 0.8) +
  # Séparation 16S / ITS côte à côte
  facet_wrap(~Dataset, scales = "free_x") + 
  coord_flip() +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), 
            hjust = -0.1, size = 3, fontface = "bold") +
  
  # Couleurs
  # scale_fill_manual(values = c("Métadonnées" = "#66c2a5", "Non Expliqué (Biologique)" = "grey50")) +
  
  # Esthétique
    theme_bw() +
  theme(
    legend.position = "none",
    panel.grid.major = element_blank(), # Enlève la grosse grille
    panel.grid.minor = element_blank(), # Enlève la petite grille
    strip.background = element_rect(fill = "white"), # Fond des titres de facettes en blanc
    strip.text = element_text(face = "bold", size = 9),
    axis.text.y = element_text(size = 10, face = "bold"),
  ) +
  labs(title = "PERMANOVA",
       subtitle = "Part de variance expliquée (R2) par chaque facteur",
       y = "Pourcentage de variance expliquée (%)",
       x = "") +
  
  # Ajustement échelle
  ylim(0, 110) 

print(p_permanova_combined)

ggsave(
  filename = here(path_figs, "p_permanova_combined.svg"),
  plot = p_permanova_combined,
  width = 6,
  height = 4,
  device = "svg"
)

```


```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)
library(svglite)

prepare_rank_abundance_poster <- function(physeq_obj, title_label) {
  # 1. taxo et top 6 global
  tax_df <- as.data.frame(tax_table(physeq_obj)) %>%
    mutate(
      Genus_Clean = gsub("g__", "", as.character(Genus)),       # clean préfixes g__ et s__
      Species_Clean = gsub("s__", "", as.character(Species)),
      Full_Name = case_when(       # abréviation sélective, quand absence espèce : sp
        is.na(Species_Clean) | Species_Clean == "" | grepl("sp", Species_Clean) ~ paste(Genus_Clean, "sp."),
        TRUE ~ paste0(substr(Genus_Clean, 1, 1), ". ", Species_Clean)
      ))
  
  # sélection des 6 ASV les plus abondants globalement
  top_global_ids <- names(sort(taxa_sums(physeq_obj), decreasing = TRUE)[1:6])
  tax_df$Temp_Name <- ifelse(rownames(tax_df) %in% top_global_ids, tax_df$Full_Name, "Autres")   # legende "autres"
  species_names <- sort(setdiff(unique(tax_df$Temp_Name), "Autres"))   # sp par ordre alphabétique et "autres" à la fin
  legend_levels <- c(species_names, "Autres")
  tax_df$Legend_Name <- factor(tax_df$Temp_Name, levels = legend_levels)

  # 2. calcul Ranks (top 10 par sample)
  otu_mat <- as.matrix(otu_table(physeq_obj))
  ranked_values <- apply(otu_mat, 2, function(x) sort(x, decreasing = TRUE)[1:10])
  ranked_ids <- apply(otu_mat, 2, function(x) names(sort(x, decreasing = TRUE))[1:10])
  
  df_long <- bind_rows(lapply(1:ncol(otu_mat), function(i) {
    data.frame(Rank = 1:10, Abundance = ranked_values[, i] * 100, ASV_ID = ranked_ids[, i])
  })) %>%
    left_join(tax_df %>% select(Legend_Name) %>% tibble::rownames_to_column("ASV_ID"), by = "ASV_ID")

  # 3. palette de couleurs (Couleurs + Gris pour Autres)
  my_colors <- setNames(c(scales::hue_pal()(length(species_names)), "#D3D3D3"), legend_levels)

  # 4. graph final
  ggplot(df_long, aes(x = as.factor(Rank), y = Abundance)) +
    geom_boxplot(outlier.shape = NA, fill = "grey95", color = "grey40", size = 0.4, na.rm = TRUE) +
    geom_jitter(aes(color = Legend_Name), width = 0.2, alpha = 0.4, size = 0.8, na.rm = TRUE) +
    scale_color_manual(values = my_colors) +
    scale_y_continuous(limits = c(0, 105), breaks = seq(0, 100, 25)) + 
    theme_bw() +
    labs(
      title = title_label, 
      x = "Rang d'abondance (Top 10 ASVs)", 
      y = "Abondance relative (%)", 
      color = "Espèces"
    ) +
    theme(
      legend.text = element_text(face = "italic", size = 6.5),
      legend.position = "right",
      legend.key.size = unit(0.3, "cm"),
      legend.margin = margin(l = -5),      
      plot.title = element_text(size = 10, face = "bold"),
      axis.title = element_text(size = 8.5, face = "plain"),
      axis.text = element_text(size = 7.5),
      plot.margin = margin(5, 5, 5, 5)
    ) +
    guides(color = guide_legend(ncol = 1))
}

p_rank_16s <- prepare_rank_abundance_poster(phylos_16s, "Bactéries (16S)")
p_rank_its <- prepare_rank_abundance_poster(phylos_its, "Levures (ITS)")

p_final <- grid.arrange(p_rank_16s, p_rank_its, ncol = 2, widths = c(1, 1))

ggsave("../results/figures/figure_dominance_poster.svg", p_final, width = 8, height = 3)
```
## Plot réseaux d'interactions (co-occurences)

```{r}
library(phyloseq)
library(tidyverse)
library(igraph)
library(ggraph)

# -- 1 : regroupement des ASVs par espèce --
ps_16s_gp <- tax_glom(phylos_16s, taxrank = "Species")
ps_its_gp <- tax_glom(phylos_its, taxrank = "Species")

# -- 2: Filtre + standardisation --
# filtrage : seuil 0.5 % abondance moyenne au minimum pour être un noeud du graphe
keep_16s <- filter_taxa(ps_16s_gp, function(x) mean(x) > 0.005, TRUE)
keep_its <- filter_taxa(ps_its_gp, function(x) mean(x) > 0.005, TRUE)

# calcul poids des noeuds par rapport à l'abondance (pour taille des points ensuite)
abund_16s <- taxa_sums(keep_16s) / nsamples(keep_16s)
abund_its <- taxa_sums(keep_its) / nsamples(keep_its)
total_abund <- c(abund_16s, abund_its)

# -- 3 : Analyse des co-occurrences (Spearman) --
# fusion des tables bacteries et fungi en une matrice pour l'analyse
combined_otu <- cbind(as.data.frame(t(otu_table(keep_16s))), 
                      as.data.frame(t(otu_table(keep_its))))
cor_matrix <- cor(combined_otu, method = "spearman")

#seuil de significativité (ignorer les relations faibles)
cor_matrix[abs(cor_matrix) < 0.13] <- 0
diag(cor_matrix) <- 0

# -- 4 : Contruction du graphe --
net <- graph_from_adjacency_matrix(cor_matrix, mode = "undirected", weighted = TRUE)
E(net)$abs_weight <- abs(E(net)$weight) 

# -- 5: Habillage taxo et métadonnées (taxo) --
# nettoyage des noms : affichage propre type G. espece , ou Genre sp. (si l'espèce est absente), ou bien ignoré si appelation "cluster" "ASV" ou "unidentified"
tax_all <- rbind(as.data.frame(tax_table(keep_16s)), as.data.frame(tax_table(keep_its))) %>%
  mutate(
    Genus = str_replace_all(Genus, "g__", ""),
    Species = str_replace_all(Species, "s__", ""),
    is_sp_invalid = is.na(Species) | Species == "" | str_detect(Species, "cluster|ASV|unidentified"),
    is_gen_invalid = is.na(Genus) | Genus == "" | str_detect(Genus, "cluster|ASV|unidentified"),
    Clean_Label = case_when(
      !is_sp_invalid ~ paste0(substr(Genus, 1, 1), ". ", Species),
      !is_gen_invalid ~ paste0(Genus, " sp."),
      TRUE ~ NA_character_
    )
  )

# Ajout des infos bio dans les noeuds 
V(net)$Species_Label <- tax_all[V(net)$name, "Clean_Label"]
V(net)$Kingdom <- ifelse(V(net)$name %in% taxa_names(keep_16s), "Bactérie", "Champignon")
V(net)$Abundance <- total_abund[V(net)$name] # ajout abondance calculée
net <- delete_vertices(net, which(is.na(V(net)$Species_Label))) #si noeud sans label, supprime

# -- 6: Visualisation du graphe + ordre de légende + noms clarifiés --
p_net_final <- ggraph(net, layout = 'fr', weights = abs_weight) + 
  geom_edge_link(aes(color = weight > 0, alpha = abs(weight)), width = 1.2) +
  geom_node_point(aes(color = Kingdom, size = Abundance)) +
  geom_node_text(aes(label = Species_Label), repel = TRUE, 
                 fontface = "italic", size = 3.2, bg.color = "white", bg.r = 0.1) +
  
  # le règne
  scale_color_manual(values = c("Bactérie" = "#66C2AE", "Champignon" = "#FF9163"),
                     name = "Règne",
                     guide = guide_legend(order = 1)) +
  
  # type interaction
  scale_edge_color_manual(values = c("TRUE" = "#2ca02c", "FALSE" = "#d62728"), 
                          name = "Interaction", 
                          labels = c("Exclusion (-)", "Co-occurrence (+)"),
                          guide = guide_legend(order = 2)) +
  
  # abondance (taille points)
  scale_size_continuous(range = c(2, 10), 
                        name = "Abondance",
                        guide = guide_legend(order = 3)) +
  
  scale_edge_alpha_continuous(name = "Force (|r|)",
                              guide = guide_legend(order = 4)) +
  
  theme_graph() +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 9.5, face = "bold"), 
    legend.text = element_text(size = 8),               
    legend.key.size = unit(0.45, "cm"),                  
    legend.margin = margin(2, 2, 2, 2),                 
    legend.spacing.y = unit(0.15, "cm")                  
  ) +
  labs(subtitle = "Corrélation Spearman |r| > 0.13, micro-organismes filtrés à abond. > 0.5%")

# Affichage et sauvegarde svg
print(p_net_final)
ggsave(
  filename = "reseau_microbiome.svg", 
  plot = p_net_final, 
  width = 7, 
  height = 5, 
  device = "svg"
)
```